In [1]:
import pandas as pd

df = pd.read_csv("../Data/ONLINE_FOOD_DELIVERY_ANALYSIS.csv")
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  str
 1   Customer_ID          100000 non-null  str
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   str
 4   City                 83274 non-null   str
 5   Area                 83315 non-null   str
 6   Restaurant_ID        100000 non-null  str
 7   Restaurant_Name      100000 non-null  str
 8   Cuisine_Type         83115 non-null   str
 9   Order_Date           98986 non-null   str
 10  Order_Time           98002 non-null   str
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   str
 17  Order_Status         100000 non-null  str
 18  Cancellation_Reason  9031 non-null    str
 19  Delivery_Partner_ID  100000 non-null  str
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  str
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(1), str(15)
memory usage: 19.1+ MB

In [3]:
df.dtypes

Order_ID                   str
Customer_ID                str
Customer_Age           float64
Customer_Gender            str
City                       str
Area                       str
Restaurant_ID              str
Restaurant_Name            str
Cuisine_Type               str
Order_Date                 str
Order_Time                 str
Delivery_Time_Min      float64
Distance_km            float64
Order_Value            float64
Discount_Applied       float64
Final_Amount           float64
Payment_Mode               str
Order_Status               str
Cancellation_Reason        str
Delivery_Partner_ID        str
Delivery_Rating        float64
Restaurant_Rating      float64
Order_Day                  str
Peak_Hour               object
Profit_Margin          float64
dtype: object

In [4]:
df.describe()

,Customer_Age,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Delivery_Rating,Restaurant_Rating,Profit_Margin
count,49907.000000,66641.000000,66530.000000,66673.000000,83285.000000,44303.000000,83477.000000,100000.000000,100000.000000
mean,38.976516,127.475923,16.449242,2081.830126,93.936243,1961.101190,2.991531,4.249680,0.150362
std,12.372157,90.805839,12.256742,1553.628891,108.209904,1557.354417,1.414108,0.722554,0.201888
min,18.000000,20.000000,1.000000,150.000000,0.000000,-150.000000,1.000000,3.000000,-0.200000
25%,28.000000,45.000000,5.470000,673.000000,20.000000,559.000000,2.000000,3.600000,-0.020000
50%,39.000000,120.000000,9.970000,1197.000000,50.000000,1156.000000,3.000000,4.200000,0.150000
75%,50.000000,210.000000,27.430000,3494.000000,100.000000,3375.000000,4.000000,4.900000,0.320000
max,60.000000,300.000000,40.000000,5000.000000,300.000000,4980.000000,5.000000,5.500000,0.500000

In [5]:
df.shape

(100000, 25)

In [6]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Age', 'Customer_Gender', 'City',
       'Area', 'Restaurant_ID', 'Restaurant_Name', 'Cuisine_Type',
       'Order_Date', 'Order_Time', 'Delivery_Time_Min', 'Distance_km',
       'Order_Value', 'Discount_Applied', 'Final_Amount', 'Payment_Mode',
       'Order_Status', 'Cancellation_Reason', 'Delivery_Partner_ID',
       'Delivery_Rating', 'Restaurant_Rating', 'Order_Day', 'Peak_Hour',
       'Profit_Margin'],
      dtype='str')

In [7]:
df.describe(include = "object")

C:\Users\SONY\AppData\Local\Temp\ipykernel_10252\3591357663.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = "object")

,Order_ID,Customer_ID,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,Order_Time,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Order_Day,Peak_Hour
count,100000,100000,75144,83274,83315,100000,100000,83115,98986,98002,80089,100000,9031,100000,100000,67038
unique,100000,8999,3,5,5,900,500,5,365,1,4,2,3,900,2,2
top,ORD000001,CUST2487,Other,Hyderabad,South,RES509,Restaurant_450,Indian,7/15/2024,0:00,Card,Delivered,Late Delivery,DP543,Weekday,False
freq,1,24,25135,16884,16725,145,246,16685,322,98002,20094,84964,3059,144,71370,33585

In [8]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors='coerce')

In [9]:
df["City"].unique()

<StringArray>
[nan, 'Chennai', 'Delhi', 'Mumbai', 'Bangalore', 'Hyderabad']
Length: 6, dtype: str

In [10]:
cat_columns = ["Customer_Gender",
    "City",
    "Area",
    "Cuisine_Type",
    "Payment_Mode",
    "Order_Status",
    "Cancellation_Reason",
    "Peak_Hour",
    "Order_Day"]

for col in cat_columns:
    df[col] = df[col].astype('category')

print(df.dtypes)

Order_ID                          str
Customer_ID                       str
Customer_Age                  float64
Customer_Gender              category
City                         category
Area                         category
Restaurant_ID                     str
Restaurant_Name                   str
Cuisine_Type                 category
Order_Date             datetime64[us]
Order_Time                        str
Delivery_Time_Min             float64
Distance_km                   float64
Order_Value                   float64
Discount_Applied              float64
Final_Amount                  float64
Payment_Mode                 category
Order_Status                 category
Cancellation_Reason          category
Delivery_Partner_ID               str
Delivery_Rating               float64
Restaurant_Rating             float64
Order_Day                    category
Peak_Hour                    category
Profit_Margin                 float64
dtype: object

In [11]:
df.isnull().sum()

Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [12]:
null_percent = df.isnull().mean() * 100
print(null_percent.sort_values(ascending=False))

Cancellation_Reason    90.969
Final_Amount           55.697
Customer_Age           50.093
Distance_km            33.470
Delivery_Time_Min      33.359
Order_Value            33.327
Peak_Hour              32.962
Customer_Gender        24.856
Payment_Mode           19.911
Cuisine_Type           16.885
City                   16.726
Discount_Applied       16.715
Area                   16.685
Delivery_Rating        16.523
Order_Time              1.998
Order_Date              1.014
Order_Day               0.000
Delivery_Partner_ID     0.000
Restaurant_Rating       0.000
Order_ID                0.000
Order_Status            0.000
Customer_ID             0.000
Restaurant_Name         0.000
Restaurant_ID           0.000
Profit_Margin           0.000
dtype: float64

In [13]:
df["Cancellation_Reason"] = df["Cancellation_Reason"].astype("object")
df["Cancellation_Reason"] = df["Cancellation_Reason"].fillna("Not Cancelled") 
df["Cancellation_Reason"] = df["Cancellation_Reason"].astype("category") 
df["Cancellation_Reason"].value_counts()

Cancellation_Reason
Not Cancelled         90969
Late Delivery          3059
Customer Cancelled     2993
Restaurant Issue       2979
Name: count, dtype: int64

In [14]:
df["Customer_Gender"] = df["Customer_Gender"].astype("object")
df["Customer_Gender"] = df["Customer_Gender"].fillna("Unknown") 
df["Customer_Gender"] = df["Customer_Gender"].astype("category") 
df["Customer_Gender"].value_counts()

Customer_Gender
Other      25135
Female     25031
Male       24978
Unknown    24856
Name: count, dtype: int64

In [15]:
df["Customer_Age"] = df["Customer_Age"].fillna(df["Customer_Age"].mean())

In [16]:
df.drop("Order_Time", axis=1, inplace=True)

In [17]:
df["Order_Date"] = df["Order_Date"].fillna(df["Order_Date"].mode()[0])
df["Discount_Applied"] = df["Discount_Applied"].fillna(0)
df["Order_Value"] = df["Order_Value"].fillna(df["Order_Value"].mean())

In [33]:
df["Delivery_Time_Min"] = df["Delivery_Time_Min"].fillna(df["Delivery_Time_Min"].mean())
df["Delivery_Time_Min"].skew()

np.float64(0.5020070471563489)

In [19]:
df["Distance_km"] = df["Distance_km"].fillna(df["Distance_km"].median())

In [20]:
df['Delivery_Rating'] = df['Delivery_Rating'].fillna(df['Delivery_Rating'].median())
df['Final_Amount'] = df['Final_Amount'].fillna(df['Order_Value'] - df['Discount_Applied'])

In [21]:
cat_cols = ['Cuisine_Type', 'City', 'Area','Peak_Hour','Payment_Mode']

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [22]:
df[["Order_Value", "Discount_Applied", "Final_Amount"]]

       Order_Value  Discount_Applied  Final_Amount
0      2081.830126               0.0   2081.830126
1      4869.000000              20.0   4849.000000
2       757.000000              20.0    737.000000
3      2081.830126               0.0   2081.830126
4       372.000000              20.0    352.000000
...            ...               ...           ...
99995   232.000000             100.0    132.000000
99996  1098.000000              20.0   1078.000000
99997  2081.830126              20.0   2061.830126
99998  2081.830126             100.0   1981.830126
99999  2909.000000               0.0   2909.000000

[100000 rows x 3 columns]

In [23]:
import os
print(os.getcwd())

c:\Users\SONY\Desktop\GUVI\Online_Food_Delivery_Analysis\NoteBook

In [24]:
null_percent = df.isnull().mean() * 100
print(null_percent.sort_values(ascending=False))

Order_ID               0.0
Customer_ID            0.0
Peak_Hour              0.0
Order_Day              0.0
Restaurant_Rating      0.0
Delivery_Rating        0.0
Delivery_Partner_ID    0.0
Cancellation_Reason    0.0
Order_Status           0.0
Payment_Mode           0.0
Final_Amount           0.0
Discount_Applied       0.0
Order_Value            0.0
Distance_km            0.0
Delivery_Time_Min      0.0
Order_Date             0.0
Cuisine_Type           0.0
Restaurant_Name        0.0
Restaurant_ID          0.0
Area                   0.0
City                   0.0
Customer_Gender        0.0
Customer_Age           0.0
Profit_Margin          0.0
dtype: float64

In [25]:
import pandas as pd

numeric_cols = ['Delivery_Time_Min', 'Order_Value']

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    

    df[col] = df[col].apply(lambda x: upper_bound if x > upper_bound else (lower_bound if x < lower_bound else x))

    print(f"{col} capped: lower={lower_bound:.2f}, upper={upper_bound:.2f}")

Delivery_Time_Min capped: lower=-102.50, upper=325.50
Order_Value capped: lower=-1777.00, upper=5455.00

In [26]:
df['Delivery_Rating'] = df['Delivery_Rating'].clip(upper=5)
df['Profit_Margin'] = df['Profit_Margin'].clip(lower=0)

In [27]:
cat_cols = df.select_dtypes(include='category').columns
print(cat_cols)

for col in cat_cols:
    df[col] = (df[col].astype(str).str.strip().str.lower().astype('category'))

print("Categorical columns standardized successfully!")

Index(['Customer_Gender', 'City', 'Area', 'Cuisine_Type', 'Payment_Mode',
       'Order_Status', 'Cancellation_Reason', 'Order_Day', 'Peak_Hour'],
      dtype='str')
Categorical columns standardized successfully!

In [28]:
inconsistent_orders = df[(df['Order_Status'] == 'cancelled') & 
     (df['Delivery_Rating'].notna() |df['Restaurant_Rating'].notna())]

print("Number of inconsistent rows:", len(inconsistent_orders))
df.loc[df['Order_Status'] == 'cancelled', 
       ['Delivery_Rating', 'Restaurant_Rating']] = pd.NA

Number of inconsistent rows: 15036

In [ ]:
df[(df['Order_Status'] == 'cancelled') & (df['Delivery_Rating'].notna() |df['Restaurant_Rating'].notna())]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Customer_Age, Customer_Gender, City, Area, Restaurant_ID, Restaurant_Name, Cuisine_Type, Order_Date, Delivery_Time_Min, Distance_km, Order_Value, Discount_Applied, Final_Amount, Payment_Mode, Order_Status, Cancellation_Reason, Delivery_Partner_ID, Delivery_Rating, Restaurant_Rating, Order_Day, Peak_Hour, Profit_Margin]
Index: []

[0 rows x 24 columns]

In [ ]:
df[(df['Order_Status'] == 'cancelled') & (df['Cancellation_Reason'].isna())]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Customer_Age, Customer_Gender, City, Area, Restaurant_ID, Restaurant_Name, Cuisine_Type, Order_Date, Delivery_Time_Min, Distance_km, Order_Value, Discount_Applied, Final_Amount, Payment_Mode, Order_Status, Cancellation_Reason, Delivery_Partner_ID, Delivery_Rating, Restaurant_Rating, Order_Day, Peak_Hour, Profit_Margin]
Index: []

[0 rows x 24 columns]

In [31]:
df['Calculated_Amount'] = df['Order_Value'] - df['Discount_Applied']

mismatch = df[df['Final_Amount'] != df['Calculated_Amount']]
print("Mismatched rows:", len(mismatch))

Mismatched rows: 0

In [32]:
df.to_csv("cleaned_data.csv", index=False)